export const invoices = {
  data: [
    {
      id: "in_1LaEDaKoFCylMjm8S1CKJbFt",
      object: "invoice",
      account_country: "SE",
      account_name: "Zephyr Valley AB",
      account_tax_ids: null,
      amount_due: 500000,
      amount_paid: 0,
      amount_remaining: 500000,
      application: null,
      application_fee_amount: null,
      attempt_count: 0,
      attempted: false,
      auto_advance: true,
      automatic_tax: {
        enabled: false,
        status: null,
      },
      billing_reason: "manual",
      charge: null,
      collection_method: "send_invoice",
      created: 1661326902,
      currency: "usd",
      custom_fields: null,
      customer: "cus_MIptVqRpu4TkI2",
      customer_address: {
        city: "Claymont",
        country: "US",
        line1: "",
        line2: "",
        postal_code: "",
        state: "DE",
      },
      customer_email: "test@customer.com",
      customer_name: "Test Customer",
      customer_phone: null,
      customer_shipping: {
        address: {
          city: "Claymont",
          country: "US",
          line1: "",
          line2: "",
          postal_code: "",
          state: "DE",
        },
        name: "Test Customer",
        phone: "",
      },
      customer_tax_exempt: "none",
      customer_tax_ids: [],
      default_payment_method: null,
      default_source: null,
      default_tax_rates: [],
      description: null,
      discount: null,
      discounts: [],
      due_date: 1663918942,
      ending_balance: 0,
      footer: null,
      hosted_invoice_url:
        "https://invoice.stripe.com/i/acct_1LaBDLKoFCylMjm8/test_YWNjdF8xTGFCRExLb0ZDeWxNam04LF9NSXB0djFPZHNTSDI3enJSNHV1OFhTR2JBdDRNMTl0LDUyMDI4ODEz0200WG9mweya?s=ap",
      invoice_pdf:
        "https://pay.stripe.com/invoice/acct_1LaBDLKoFCylMjm8/test_YWNjdF8xTGFCRExLb0ZDeWxNam04LF9NSXB0djFPZHNTSDI3enJSNHV1OFhTR2JBdDRNMTl0LDUyMDI4ODEz0200WG9mweya/pdf?s=ap",
      last_finalization_error: null,
      livemode: false,
      metadata: {},
      next_payment_attempt: null,
      number: "AFB9CE85-0001",
      on_behalf_of: null,
      paid: false,
      paid_out_of_band: false,
      payment_intent: "pi_3LaEEEKoFCylMjm81qfZ8SP7",
      payment_settings: {
        default_mandate: null,
        payment_method_options: null,
        payment_method_types: ["card"],
      },
      period_end: 1661326902,
      period_start: 1661326902,
      post_payment_credit_notes_amount: 0,
      pre_payment_credit_notes_amount: 0,
      quote: null,
      receipt_number: null,
      rendering_options: null,
      starting_balance: 0,
      statement_descriptor: null,
      status: "open",
      status_transitions: {
        finalized_at: 1661326942,
        marked_uncollectible_at: null,
        paid_at: null,
        voided_at: null,
      },
      subscription: null,
      subtotal: 500000,
      subtotal_excluding_tax: 500000,
      tax: null,
      test_clock: null,
      total: 700000,
      total_discount_amounts: [],
      total_excluding_tax: 500000,
      total_tax_amounts: [],
      transfer_data: null,
      webhooks_delivered_at: 1661326902,
    },
    {
      id: "in_1LaEDaKoFCylMjm8S1CKJbFt",
      object: "invoice",
      account_country: "SE",
      account_name: "Zephyr Valley AB",
      account_tax_ids: null,
      amount_due: 500000,
      amount_paid: 0,
      amount_remaining: 500000,
      application: null,
      application_fee_amount: null,
      attempt_count: 0,
      attempted: false,
      auto_advance: true,
      automatic_tax: {
        enabled: false,
        status: null,
      },
      billing_reason: "manual",
      charge: null,
      collection_method: "send_invoice",
      created: +new Date(1661326902 - 1 * 3600 * 24 * 30),
      currency: "usd",
      custom_fields: null,
      customer: "cus_MIptVqRpu4TkI2",
      customer_address: {
        city: "Claymont",
        country: "US",
        line1: "",
        line2: "",
        postal_code: "",
        state: "DE",
      },
      customer_email: "test@customer.com",
      customer_name: "Test Customer",
      customer_phone: null,
      customer_shipping: {
        address: {
          city: "Claymont",
          country: "US",
          line1: "",
          line2: "",
          postal_code: "",
          state: "DE",
        },
        name: "Test Customer",
        phone: "",
      },
      customer_tax_exempt: "none",
      customer_tax_ids: [],
      default_payment_method: null,
      default_source: null,
      default_tax_rates: [],
      description: null,
      discount: null,
      discounts: [],
      due_date: +new Date(1663918942 - 1 * 3600 * 24 * 30),
      ending_balance: 0,
      footer: null,
      hosted_invoice_url:
        "https://invoice.stripe.com/i/acct_1LaBDLKoFCylMjm8/test_YWNjdF8xTGFCRExLb0ZDeWxNam04LF9NSXB0djFPZHNTSDI3enJSNHV1OFhTR2JBdDRNMTl0LDUyMDI4ODEz0200WG9mweya?s=ap",
      invoice_pdf:
        "https://pay.stripe.com/invoice/acct_1LaBDLKoFCylMjm8/test_YWNjdF8xTGFCRExLb0ZDeWxNam04LF9NSXB0djFPZHNTSDI3enJSNHV1OFhTR2JBdDRNMTl0LDUyMDI4ODEz0200WG9mweya/pdf?s=ap",
      last_finalization_error: null,
      lines: {
        object: "list",
        data: [
          {
            id: "il_1LaEDsKoFCylMjm8XEz7pIkq",
            object: "line_item",
            amount: 500000,
            amount_excluding_tax: 500000,
            currency: "usd",
            description: "Freelance service",
            discount_amounts: [],
            discountable: true,
            discounts: [],
            invoice_item: "ii_1LaEDsKoFCylMjm8gUBgnAZI",
            livemode: false,
            metadata: {},
            period: {
              end: 1661326920,
              start: 1661326920,
            },
            plan: null,
            price: {
              id: "price_1LaEDrKoFCylMjm8vXsbroMv",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1661326919,
              currency: "usd",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: null,
              metadata: {},
              nickname: null,
              product: "prod_MIptDAJd1polMT",
              recurring: null,
              tax_behavior: "unspecified",
              tiers_mode: null,
              transform_quantity: null,
              type: "one_time",
              unit_amount: 500000,
              unit_amount_decimal: "500000",
            },
            proration: false,
            proration_details: {
              credited_items: null,
            },
            quantity: 1,
            subscription: null,
            tax_amounts: [],
            tax_rates: [],
            type: "invoiceitem",
            unit_amount_excluding_tax: "500000",
          },
        ],
        has_more: false,
        total_count: 1,
        url: "/v1/invoices/in_1LaEDaKoFCylMjm8S1CKJbFt/lines",
      },
      livemode: false,
      metadata: {},
      next_payment_attempt: null,
      number: "AFB9CE85-0001",
      on_behalf_of: null,
      paid: false,
      paid_out_of_band: false,
      payment_intent: "pi_3LaEEEKoFCylMjm81qfZ8SP7",
      payment_settings: {
        default_mandate: null,
        payment_method_options: null,
        payment_method_types: ["card"],
      },
      period_end: 1661326902,
      period_start: 1661326902,
      post_payment_credit_notes_amount: 0,
      pre_payment_credit_notes_amount: 0,
      quote: null,
      receipt_number: null,
      rendering_options: null,
      starting_balance: 0,
      statement_descriptor: null,
      status: "paid",
      status_transitions: {
        finalized_at: 1661326942,
        marked_uncollectible_at: null,
        paid_at: null,
        voided_at: null,
      },
      subscription: null,
      subtotal: 500000,
      subtotal_excluding_tax: 500000,
      tax: null,
      test_clock: null,
      total: 500000,
      total_discount_amounts: [],
      total_excluding_tax: 500000,
      total_tax_amounts: [],
      transfer_data: null,
      webhooks_delivered_at: 1661326902,
    },
  ],
};

export const tx = [
  {
    blockNum: "0x71e53f",
    uniqueId:
      "0x16699e5cf88d46e0116dae46f9adfe3e636751d27b5d989c27c406dda9eff96f:log:85",
    hash: "0x16699e5cf88d46e0116dae46f9adfe3e636751d27b5d989c27c406dda9eff96f",
    from: "0x15a411507e901f26965f0ebcd3155834b058a6b2",
    to: "0xd5c94d0bfca611e3bf61228e85fc5374c4deb4c0",
    value: 5000,
    erc721TokenId: null,
    erc1155Metadata: null,
    tokenId: null,
    asset: "USDC",
    category: "erc20",
    rawContract: {
      value: "0x2710",
      address: "0x10e0c161caabd66da8bcf60833f8db9206f8f6ab",
      decimal: "0x4",
    },
    metadata: {
      blockTimestamp: "2022-08-24T14:50:48.000Z",
    },
  },
];
